import AppKit
import Foundation

struct ClipboardPasteboardRepresentation: Codable, Equatable, Sendable {
    let itemIndex: Int
    let typeIdentifier: String
    let data: Data

    init(
        itemIndex: Int = 0,
        typeIdentifier: String,
        data: Data
    ) {
        self.itemIndex = itemIndex
        self.typeIdentifier = typeIdentifier
        self.data = data
    }
}

enum PasteboardRepresentationPolicy {
    static let maxRepresentationCount = 16
    static let maxRepresentationByteCount = 256 * 1_024
    static let maxTotalByteCount = 512 * 1_024

    static let sourcePasteboardTypeRawValue = "org.nspasteboard.source"

    static let ignoredPasteboardTypeRawValues: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb"
    ]

    private static let excludedRepresentationTypeRawValues =
        ignoredPasteboardTypeRawValues.union([
            sourcePasteboardTypeRawValue
        ])

    static func shouldIgnore(
        pasteboardTypes: [NSPasteboard.PasteboardType]
    ) -> Bool {
        pasteboardTypes.contains {
            ignoredPasteboardTypeRawValues.contains($0.rawValue)
        }
    }

    static func retainedRepresentations(
        from pasteboard: NSPasteboard,
        rootTypes: [NSPasteboard.PasteboardType]
    ) -> [ClipboardPasteboardRepresentation] {
        if let pasteboardItems = pasteboard.pasteboardItems,
           !pasteboardItems.isEmpty {
            return retainedRepresentations(
                pasteboardItems.enumerated().flatMap { index, item in
                    item.types.compactMap { type in
                        item.data(forType: type).map {
                            RepresentationCandidate(
                                itemIndex: index,
                                type: type,
                                data: $0
                            )
                        }
                    }
                }
            )
        }

        return retainedRepresentations(
            rootTypes.compactMap { type in
                pasteboard.data(forType: type).map {
                    RepresentationCandidate(
                        itemIndex: 0,
                        type: type,
                        data: $0
                    )
                }
            }
        )
    }

    private static func retainedRepresentations(
        _ candidates: [RepresentationCandidate]
    ) -> [ClipboardPasteboardRepresentation] {
        var retained: [ClipboardPasteboardRepresentation] = []
        retained.reserveCapacity(min(candidates.count, maxRepresentationCount))
        var retainedKeys: Set<String> = []
        var totalByteCount = 0

        for candidate in candidates {
            guard retained.count < maxRepresentationCount else { break }
            guard !excludedRepresentationTypeRawValues.contains(candidate.type.rawValue),
                  !candidate.data.isEmpty,
                  candidate.data.count <= maxRepresentationByteCount,
                  totalByteCount + candidate.data.count <= maxTotalByteCount else {
                continue
            }

            let key = "\(candidate.itemIndex)\u{1F}\(candidate.type.rawValue)"
            guard retainedKeys.insert(key).inserted else { continue }

            retained.append(
                ClipboardPasteboardRepresentation(
                    itemIndex: candidate.itemIndex,
                    typeIdentifier: candidate.type.rawValue,
                    data: candidate.data
                )
            )
            totalByteCount += candidate.data.count
        }

        return retained
    }

    private struct RepresentationCandidate {
        let itemIndex: Int
        let type: NSPasteboard.PasteboardType
        let data: Data
    }
}
